from tkinter import *

# Raiz de la aplicación
root = Tk()
root.config(bd=15, relief="ridge", bg="blanchedalmond")
root.title("Indice de Operaciones")
frame = Frame(root)
frame.pack()
frame.config(width=1100, height=800, bg="blanchedalmond")


# Definiciones de comandos
def tiny():
    # if para remplazar sff por tiny
    if sff1.winfo_ismapped():
        sff1.place_forget()
        sff2.place_forget()
        sff3.place_forget()
        sff4.place_forget()
        sff5.place_forget()
        sff6.place_forget()
        sff7.place_forget()
        sff8.place_forget()
        sff9.place_forget()
        sff10.place_forget()
        sff11.place_forget()
        sff12.place_forget()
        tiny1.place(x=180, y=80)
        tiny2.place(x=180, y=140)
        tiny3.place(x=180, y=200)
        tiny4.place(x=180, y=260)
        tiny5.place(x=180, y=320)
        tiny6.place(x=180, y=380)
        tiny7.place(x=180, y=440)
        tiny8.place(x=330, y=80)
        tiny9.place(x=330, y=140)
        tiny10.place(x=330, y=200)
        tiny11.place(x=330, y=260)
        tiny12.place(x=330, y=320)
        tiny13.place(x=330, y=380)
        tinyboton.configure(text="TINY ->")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # else para cuando no hay botones en la pantalla
    else:
        tinyboton.configure(text="TINY ->")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
        tiny1.place(x=180, y=80)
        tiny2.place(x=180, y=140)
        tiny3.place(x=180, y=200)
        tiny4.place(x=180, y=260)
        tiny5.place(x=180, y=320)
        tiny6.place(x=180, y=380)
        tiny7.place(x=180, y=440)
        tiny8.place(x=330, y=80)
        tiny9.place(x=330, y=140)
        tiny10.place(x=330, y=200)
        tiny11.place(x=330, y=260)
        tiny12.place(x=330, y=320)
        tiny13.place(x=330, y=380)
    # if para remplazar aio por tiny
    if aio1.winfo_ismapped():
        aio1.place_forget()
        aio2.place_forget()
        aio3.place_forget()
        aio4.place_forget()
        aio5.place_forget()
        aio6.place_forget()
        aio7.place_forget()
        tiny1.place(x=180, y=80)
        tiny2.place(x=180, y=140)
        tiny3.place(x=180, y=200)
        tiny4.place(x=180, y=260)
        tiny5.place(x=180, y=320)
        tiny6.place(x=180, y=380)
        tiny7.place(x=180, y=440)
        tiny8.place(x=330, y=80)
        tiny9.place(x=330, y=140)
        tiny10.place(x=330, y=200)
        tiny11.place(x=330, y=260)
        tiny12.place(x=330, y=320)
        tiny13.place(x=330, y=380)
        tinyboton.configure(text="TINY ->")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # if para quitar los botones de tiny
    if tiny1.winfo_ismapped():
        tiny1.place_forget()
        tiny2.place_forget()
        tiny3.place_forget()
        tiny4.place_forget()
        tiny5.place_forget()
        tiny6.place_forget()
        tiny7.place_forget()
        tiny8.place_forget()
        tiny9.place_forget()
        tiny10.place_forget()
        tiny11.place_forget()
        tiny12.place_forget()
        tiny13.place_forget()
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # if para remplazar twr por tiny
    if twr1.winfo_ismapped():
        twr1.place_forget()
        twr2.place_forget()
        twr3.place_forget()
        twr4.place_forget()
        twr5.place_forget()
        twr6.place_forget()
        twr7.place_forget()
        twr8.place_forget()
        twr9.place_forget()
        twr10.place_forget()
        twr11.place_forget()
        twr12.place_forget()
        twr13.place_forget()
        twr14.place_forget()
        twr15.place_forget()
        twr16.place_forget()
        twr17.place_forget()
        twr18.place_forget()
        tiny1.place(x=180, y=80)
        tiny2.place(x=180, y=140)
        tiny3.place(x=180, y=200)
        tiny4.place(x=180, y=260)
        tiny5.place(x=180, y=320)
        tiny6.place(x=180, y=380)
        tiny7.place(x=180, y=440)
        tiny8.place(x=330, y=80)
        tiny9.place(x=330, y=140)
        tiny10.place(x=330, y=200)
        tiny11.place(x=330, y=260)
        tiny12.place(x=330, y=320)
        tiny13.place(x=330, y=380)
        tinyboton.configure(text="TINY ->")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")


def sff():
    # if para remplazar tiny por sff
    if tiny1.winfo_ismapped():
        tiny1.place_forget()
        tiny2.place_forget()
        tiny3.place_forget()
        tiny4.place_forget()
        tiny5.place_forget()
        tiny6.place_forget()
        tiny7.place_forget()
        tiny8.place_forget()
        tiny9.place_forget()
        tiny10.place_forget()
        tiny11.place_forget()
        tiny12.place_forget()
        tiny13.place_forget()
        sff1.place(x=180, y=80)
        sff2.place(x=180, y=140)
        sff3.place(x=180, y=200)
        sff4.place(x=180, y=260)
        sff5.place(x=180, y=320)
        sff6.place(x=180, y=380)
        sff7.place(x=180, y=440)
        sff8.place(x=330, y=80)
        sff9.place(x=330, y=140)
        sff10.place(x=330, y=200)
        sff11.place(x=330, y=260)
        sff12.place(x=330, y=320)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF ->")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # else para cuando no hay botones en pantalla
    else:
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF ->")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
        sff1.place(x=180, y=80)
        sff2.place(x=180, y=140)
        sff3.place(x=180, y=200)
        sff4.place(x=180, y=260)
        sff5.place(x=180, y=320)
        sff6.place(x=180, y=380)
        sff7.place(x=180, y=440)
        sff8.place(x=330, y=80)
        sff9.place(x=330, y=140)
        sff10.place(x=330, y=200)
        sff11.place(x=330, y=260)
        sff12.place(x=330, y=320)
    # if para remplazar aio por sff
    if aio1.winfo_ismapped():
        aio1.place_forget()
        aio2.place_forget()
        aio3.place_forget()
        aio4.place_forget()
        aio5.place_forget()
        aio6.place_forget()
        aio7.place_forget()
        sff1.place(x=180, y=80)
        sff2.place(x=180, y=140)
        sff3.place(x=180, y=200)
        sff4.place(x=180, y=260)
        sff5.place(x=180, y=320)
        sff6.place(x=180, y=380)
        sff7.place(x=180, y=440)
        sff8.place(x=330, y=80)
        sff9.place(x=330, y=140)
        sff10.place(x=330, y=200)
        sff11.place(x=330, y=260)
        sff12.place(x=330, y=320)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF ->")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # if para quitar los botones de sff
    if sff1.winfo_ismapped():
        sff1.place_forget()
        sff2.place_forget()
        sff3.place_forget()
        sff4.place_forget()
        sff5.place_forget()
        sff6.place_forget()
        sff7.place_forget()
        sff8.place_forget()
        sff9.place_forget()
        sff10.place_forget()
        sff11.place_forget()
        sff12.place_forget()
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # if para remplazar twr por sff
    if twr1.winfo_ismapped():
        twr1.place_forget()
        twr2.place_forget()
        twr3.place_forget()
        twr4.place_forget()
        twr5.place_forget()
        twr6.place_forget()
        twr7.place_forget()
        twr8.place_forget()
        twr9.place_forget()
        twr10.place_forget()
        twr11.place_forget()
        twr12.place_forget()
        twr13.place_forget()
        twr14.place_forget()
        twr15.place_forget()
        twr16.place_forget()
        twr17.place_forget()
        twr18.place_forget()
        sff1.place(x=180, y=80)
        sff2.place(x=180, y=140)
        sff3.place(x=180, y=200)
        sff4.place(x=180, y=260)
        sff5.place(x=180, y=320)
        sff6.place(x=180, y=380)
        sff7.place(x=180, y=440)
        sff8.place(x=330, y=80)
        sff9.place(x=330, y=140)
        sff10.place(x=330, y=200)
        sff11.place(x=330, y=260)
        sff12.place(x=330, y=320)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF ->")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")


def aio():
    # if para remplazar tiny por aio
    if tiny1.winfo_ismapped():
        tiny1.place_forget()
        tiny2.place_forget()
        tiny3.place_forget()
        tiny4.place_forget()
        tiny5.place_forget()
        tiny6.place_forget()
        tiny7.place_forget()
        tiny8.place_forget()
        tiny9.place_forget()
        tiny10.place_forget()
        tiny11.place_forget()
        tiny12.place_forget()
        tiny13.place_forget()
        aio1.place(x=180, y=80)
        aio2.place(x=180, y=140)
        aio3.place(x=180, y=200)
        aio4.place(x=180, y=260)
        aio5.place(x=180, y=320)
        aio6.place(x=180, y=380)
        aio7.place(x=180, y=440)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO ->")
        twrboton.configure(text="TWR")
    # else para cuando no hay botones en pantalla
    else:
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO ->")
        twrboton.configure(text="TWR")
        aio1.place(x=180, y=80)
        aio2.place(x=180, y=140)
        aio3.place(x=180, y=200)
        aio4.place(x=180, y=260)
        aio5.place(x=180, y=320)
        aio6.place(x=180, y=380)
        aio7.place(x=180, y=440)
    # if para remplazar sff por aio
    if sff1.winfo_ismapped():
        sff1.place_forget()
        sff2.place_forget()
        sff3.place_forget()
        sff4.place_forget()
        sff5.place_forget()
        sff6.place_forget()
        sff7.place_forget()
        sff8.place_forget()
        sff9.place_forget()
        sff10.place_forget()
        sff11.place_forget()
        sff12.place_forget()
        aio1.place(x=180, y=80)
        aio2.place(x=180, y=140)
        aio3.place(x=180, y=200)
        aio4.place(x=180, y=260)
        aio5.place(x=180, y=320)
        aio6.place(x=180, y=380)
        aio7.place(x=180, y=440)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO ->")
        twrboton.configure(text="TWR")
    # if para quitar los botones de aio
    if aio1.winfo_ismapped():
        aio1.place_forget()
        aio2.place_forget()
        aio3.place_forget()
        aio4.place_forget()
        aio5.place_forget()
        aio6.place_forget()
        aio7.place_forget()
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # if para remplazar twr por aio
    if twr1.winfo_ismapped():
        twr1.place_forget()
        twr2.place_forget()
        twr3.place_forget()
        twr4.place_forget()
        twr5.place_forget()
        twr6.place_forget()
        twr7.place_forget()
        twr8.place_forget()
        twr9.place_forget()
        twr10.place_forget()
        twr11.place_forget()
        twr12.place_forget()
        twr13.place_forget()
        twr14.place_forget()
        twr15.place_forget()
        twr16.place_forget()
        twr17.place_forget()
        twr18.place_forget()
        aio1.place(x=180, y=80)
        aio2.place(x=180, y=140)
        aio3.place(x=180, y=200)
        aio4.place(x=180, y=260)
        aio5.place(x=180, y=320)
        aio6.place(x=180, y=380)
        aio7.place(x=180, y=440)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO ->")
        twrboton.configure(text="TWR")


def twr():
    # if para remplazar tiny por twr
    if tiny1.winfo_ismapped():
        tiny1.place_forget()
        tiny2.place_forget()
        tiny3.place_forget()
        tiny4.place_forget()
        tiny5.place_forget()
        tiny6.place_forget()
        tiny7.place_forget()
        tiny8.place_forget()
        tiny9.place_forget()
        tiny10.place_forget()
        tiny11.place_forget()
        tiny12.place_forget()
        tiny13.place_forget()
        twr1.place(x=180, y=80)
        twr2.place(x=180, y=140)
        twr3.place(x=180, y=200)
        twr4.place(x=180, y=260)
        twr5.place(x=180, y=320)
        twr6.place(x=180, y=380)
        twr7.place(x=180, y=440)
        twr8.place(x=330, y=80)
        twr9.place(x=330, y=140)
        twr10.place(x=330, y=200)
        twr11.place(x=330, y=260)
        twr12.place(x=330, y=320)
        twr13.place(x=330, y=380)
        twr14.place(x=180, y=500)
        twr15.place(x=180, y=560)
        twr16.place(x=330, y=440)
        twr17.place(x=330, y=500)
        twr18.place(x=330, y=560)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR ->")
    # else para cuando no hay botones en pantalla
    else:
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR ->")
        twr1.place(x=180, y=80)
        twr2.place(x=180, y=140)
        twr3.place(x=180, y=200)
        twr4.place(x=180, y=260)
        twr5.place(x=180, y=320)
        twr6.place(x=180, y=380)
        twr7.place(x=180, y=440)
        twr8.place(x=330, y=80)
        twr9.place(x=330, y=140)
        twr10.place(x=330, y=200)
        twr11.place(x=330, y=260)
        twr12.place(x=330, y=320)
        twr13.place(x=330, y=380)
        twr14.place(x=180, y=500)
        twr15.place(x=180, y=560)
        twr16.place(x=330, y=440)
        twr17.place(x=330, y=500)
        twr18.place(x=330, y=560)
    # if para remplazar sff por twr
    if sff1.winfo_ismapped():
        sff1.place_forget()
        sff2.place_forget()
        sff3.place_forget()
        sff4.place_forget()
        sff5.place_forget()
        sff6.place_forget()
        sff7.place_forget()
        sff8.place_forget()
        sff9.place_forget()
        sff10.place_forget()
        sff11.place_forget()
        sff12.place_forget()
        twr1.place(x=180, y=80)
        twr2.place(x=180, y=140)
        twr3.place(x=180, y=200)
        twr4.place(x=180, y=260)
        twr5.place(x=180, y=320)
        twr6.place(x=180, y=380)
        twr7.place(x=180, y=440)
        twr8.place(x=330, y=80)
        twr9.place(x=330, y=140)
        twr10.place(x=330, y=200)
        twr11.place(x=330, y=260)
        twr12.place(x=330, y=320)
        twr13.place(x=330, y=380)
        twr14.place(x=180, y=500)
        twr15.place(x=180, y=560)
        twr16.place(x=330, y=440)
        twr17.place(x=330, y=500)
        twr18.place(x=330, y=560)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR ->")
    # if para quitar los botones de twr
    if twr1.winfo_ismapped():
        twr1.place_forget()
        twr2.place_forget()
        twr3.place_forget()
        twr4.place_forget()
        twr5.place_forget()
        twr6.place_forget()
        twr7.place_forget()
        twr8.place_forget()
        twr9.place_forget()
        twr10.place_forget()
        twr11.place_forget()
        twr12.place_forget()
        twr13.place_forget()
        twr14.place_forget()
        twr15.place_forget()
        twr16.place_forget()
        twr17.place_forget()
        twr18.place_forget()
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR")
    # if para remplazar aio por twr
    if aio1.winfo_ismapped():
        aio1.place_forget()
        aio2.place_forget()
        aio3.place_forget()
        aio4.place_forget()
        aio5.place_forget()
        aio6.place_forget()
        aio7.place_forget()
        twr1.place(x=180, y=80)
        twr2.place(x=180, y=140)
        twr3.place(x=180, y=200)
        twr4.place(x=180, y=260)
        twr5.place(x=180, y=320)
        twr6.place(x=180, y=380)
        twr7.place(x=180, y=440)
        twr8.place(x=330, y=80)
        twr9.place(x=330, y=140)
        twr10.place(x=330, y=200)
        twr11.place(x=330, y=260)
        twr12.place(x=330, y=320)
        twr13.place(x=330, y=380)
        twr14.place(x=180, y=500)
        twr15.place(x=180, y=560)
        twr16.place(x=330, y=440)
        twr17.place(x=330, y=500)
        twr18.place(x=330, y=560)
        tinyboton.configure(text="TINY")
        sffboton.configure(text="SFF")
        aioboton.configure(text="AIO")
        twrboton.configure(text="TWR ->")

def CuadroDeTexto(Texto):
    texto.delete(1.0, "end")
    texto.insert(1.0, Texto)

# Botones de Mecanicos
tituloMecanico = Label(root, text="Mecanicos")
tituloMecanico.place(x=30, y=30)
tituloMecanico.config(bg="blanchedalmond", fg="navy", font=710)

tinyboton = Button(root, text="TINY")
tinyboton.place(x=30, y=80)
tinyboton.config(bg="orange", fg="black", height=2, width=14, font=1, command=tiny)

sffboton = Button(root, text="SFF")
sffboton.place(x=30, y=140)
sffboton.config(bg="limegreen", fg="black", height=2, width=14, font=1, command=sff)

aioboton = Button(root, text="AIO")
aioboton.place(x=30, y=200)
aioboton.config(bg="gold", fg="black", height=2, width=14, font=1, command=aio)

twrboton = Button(root, text="TWR")
twrboton.place(x=30, y=260)
twrboton.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1, command=twr)

# Botones Place 1 x=180 y=80
tiny1 = Button(root, text="ENFIELD")
tiny1.config(bg="orange", fg="black", height=2, width=14, font=1,
             command=lambda:CuadroDeTexto("HOLA \n"
                                          "Probando\n"
                                          "texto de Enfield"))

sff1 = Button(root, text="DUKE")
sff1.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio1 = Button(root, text="MACAO")
aio1.config(bg="gold", fg="black", height=2, width=14, font=1)

twr1 = Button(root, text="PALAU")
twr1.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 2 x=180 y=140
tiny2 = Button(root, text="DAKOTA")
tiny2.config(bg="orange", fg="black", height=2, width=14, font=1)

sff2 = Button(root, text="DUBAI")
sff2.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio2 = Button(root, text="MONTANA")
aio2.config(bg="gold", fg="black", height=2, width=14, font=1)

twr2 = Button(root, text="MOFUSHI")
twr2.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 3 x=180 y=200
tiny3 = Button(root, text="PALAU")
tiny3.config(bg="orange", fg="black", height=2, width=14, font=1)

sff3 = Button(root, text="EDMONTON")
sff3.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio3 = Button(root, text="AKS")
aio3.config(bg="gold", fg="black", height=2, width=14, font=1)

twr3 = Button(root, text="MANSFIELD")
twr3.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 4 x=180 y=260
tiny4 = Button(root, text="MOFUSHI")
tiny4.config(bg="orange", fg="black", height=2, width=14, font=1)

sff4 = Button(root, text="ECUADOR")
sff4.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio4 = Button(root, text="AKSA")
aio4.config(bg="gold", fg="black", height=2, width=14, font=1)

twr4 = Button(root, text="PAROS")
twr4.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 5 x=180 y=320
tiny5 = Button(root, text="DOVER")
tiny5.config(bg="orange", fg="black", height=2, width=14, font=1)

sff5 = Button(root, text="MUSTANG")
sff5.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio5 = Button(root, text="AEG")
aio5.config(bg="gold", fg="black", height=2, width=14, font=1)

twr5 = Button(root, text="METHUEN")
twr5.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 6 x=180 y=380
tiny6 = Button(root, text="MANSFIELD")
tiny6.config(bg="orange", fg="black", height=2, width=14, font=1)

sff6 = Button(root, text="DAKAR")
sff6.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio6 = Button(root, text="AEGA")
aio6.config(bg="gold", fg="black", height=2, width=14, font=1)

twr6 = Button(root, text="PRAGUE")
twr6.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 7 x=180 y=440
tiny7 = Button(root, text="ETON")
tiny7.config(bg="orange", fg="black", height=2, width=14, font=1)

sff7 = Button(root, text="PALAU")
sff7.config(bg="limegreen", fg="black", height=2, width=14, font=1)

aio7 = Button(root, text="ADEN")
aio7.config(bg="gold", fg="black", height=2, width=14, font=1)

twr7 = Button(root, text="MANILA")
twr7.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 8 x=330 y=80
tiny8 = Button(root, text="DUKE")
tiny8.config(bg="orange", fg="black", height=2, width=14, font=1)

sff8 = Button(root, text="MOFUSHI")
sff8.config(bg="limegreen", fg="black", height=2, width=14, font=1)

twr8 = Button(root, text="MALE")
twr8.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 9 x=330 y=140
tiny9 = Button(root, text="PAROS")
tiny9.config(bg="orange", fg="black", height=2, width=14, font=1)

sff9 = Button(root, text="MALAYSIA")
sff9.config(bg="limegreen", fg="black", height=2, width=14, font=1)

twr9 = Button(root, text="MADRID")
twr9.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 10 x=330 y=200
tiny10 = Button(root, text="PRINCETON")
tiny10.config(bg="orange", fg="black", height=2, width=14, font=1)

sff10 = Button(root, text="METZ")
sff10.config(bg="limegreen", fg="black", height=2, width=14, font=1)

twr10 = Button(root, text="BARKLEY")
twr10.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 11 x=330 y=260
tiny11 = Button(root, text="NANO")
tiny11.config(bg="orange", fg="black", height=2, width=14, font=1)

sff11 = Button(root, text="MANSFIELD")
sff11.config(bg="limegreen", fg="black", height=2, width=14, font=1)

twr11 = Button(root, text="VIPER")
twr11.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 12 x=330 y=320
tiny12 = Button(root, text="PIPPEN")
tiny12.config(bg="orange", fg="black", height=2, width=14, font=1)

sff12 = Button(root, text="PAROS")
sff12.config(bg="limegreen", fg="black", height=2, width=14, font=1)

twr12 = Button(root, text="BIRD")
twr12.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 13 x=330 y=380
tiny13 = Button(root, text="CAMARO")
tiny13.config(bg="orange", fg="black", height=2, width=14, font=1)

twr13 = Button(root, text="JORDAN")
twr13.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 14 x=180 y=500
twr14 = Button(root, text="MAGIC")
twr14.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 15 x=180 y=560
twr15 = Button(root, text="WOLVERINE")
twr15.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 16 x=330 y=440
twr16 = Button(root, text="WILDTHING")
twr16.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 17 x=330 y=500
twr17 = Button(root, text="RIDDLER")
twr17.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Botones Place 18 x=330 y=560
twr18 = Button(root, text="LEGION")
twr18.config(bg="mediumturquoise", fg="black", height=2, width=14, font=1)

# Display de informacion
texto = Text(root)
texto.place(x=560, y=80)
texto.config(width=60, height=40)

root.mainloop()
